Add time exceeded flow for fip
ovn-org/ovn pull request #230
Opened 2023-12-27 08:40 UTC by ts170710

#211 https://github.com/ovn-org/ovn/issues/211 Add "ip4.src == <external_ip>" to match for distinguish between external router gateway and floatingIP to handle time exceeded packet.

2024-01-23 13:31 UTC, dceara commented
> @ts170710 Thanks for your PR!
> 
> I guess I'm not sure I understand how this is supposed to be useful. We already have flows in IP_INPUT stage that check for `ip.ttl == {0, 1} && !ip.later_frag` packets and reply with Time Exceeded for those. Why isn't that enough?

@ts170710 just in case you missed my question above.

Thanks,
Dumitru

2024-02-28 09:12 UTC, ts170710 commented
> > @ts170710 Thanks for your PR!
> > I guess I'm not sure I understand how this is supposed to be useful. We already have flows in IP_INPUT stage that check for `ip.ttl == {0, 1} && !ip.later_frag` packets and reply with Time Exceeded for those. Why isn't that enough?
> 
> @ts170710 just in case you missed my question above.
> 
> Thanks, Dumitru

@dceara Thank you for your comment!
As described in #211, `ip.ttl == {0, 1} ` treats floatingIPs and router gateway IPs together. When traceroute to cloud instances associated with the router, the router gateway IP address gets replaced by ` ip4.dst <-> ip4.src`,  resulting in the inability to display the router gateway IP address in the traceroute results.

2024-03-01 15:19 UTC, dceara requested changes
Please add a new system test for the scenarios you're fixing now.

Also, your change seems to break existing system tests, e.g.:
https://github.com/ovn-org/ovn/actions/runs/7346305995/job/20000851003?pr=230#step:7:4323

```
  41: system-ovn.at:3597 DNAT and SNAT on distributed router - N/S - IPv6 -- ovn-northd -- parallelization=yes -- ovn_monitor_all=yes
      ovnnat
  42: system-ovn.at:3597 DNAT and SNAT on distributed router - N/S - IPv6 -- ovn-northd -- parallelization=yes -- ovn_monitor_all=no
      ovnnat
  45: system-ovn.at:3941 DNAT and SNAT on distributed router - E/W - IPv6 -- ovn-northd -- parallelization=yes -- ovn_monitor_all=yes
      ovnnat
  46: system-ovn.at:3941 DNAT and SNAT on distributed router - E/W - IPv6 -- ovn-northd -- parallelization=yes -- ovn_monitor_all=no
      ovnnat
```

2024-03-01 15:19 UTC, dceara commented on northd/northd.c
> +                ds_put_format(match, "ip4.src == %s && ", nat_entry->nb->external_ip);
What about IPv6?  Why only on l3dgw ports?  Why not on gw routers too?

2025-04-24 05:39 UTC, almusil commented
Hi,
Sorry for the huge delay, is there any plan to continue with this PR? If not please close it or I'll close this next week in case there isn't any response.

Thanks,
Ales

2025-05-05 13:36 UTC, almusil commented
Closing the PR, please re-open/open PR with rebased version and addressed comments if there is still desire to continue with this work.

2025-05-05 13:36 UTC, closed without merging