Add support for DHCP Options 44,46 (NB Name Server, NB Node Type)
ovn-org/ovn pull request #66
Opened 2020-12-14 20:48 UTC by odivlad

Signed-off-by: Vladislav Odintsov <odivlad@gmail.com>

2020-12-21 11:36 UTC, odivlad commented
@numansiddique, Hi, could you please take a look on this?

2020-12-21 11:53 UTC, numansiddique commented on ovn-nb.xml
> +        <column name="options" key="netbios_node_type">
The patch LGTM.

Can you please move the documentation for this option  - netbios_node_type to the appropriate section i.e here - https://github.com/ovn-org/ovn/blob/master/ovn-nb.xml#L3115

2020-12-21 11:54 UTC, numansiddique requested changes
Can you please update the documentation changes I requested.

2020-12-21 12:19 UTC, numansiddique commented
Actually never mind.
I updated the documentation and submitted the patch  for review in the ML here - https://patchwork.ozlabs.org/project/ovn/patch/20201221121807.110437-1-numans@ovn.org/

The patch LGTM.

2020-12-21 13:31 UTC, numansiddique commented
Applied the patch. Closing the PR.

https://github.com/ovn-org/ovn/commit/dcbec3861802d6ec2b3684f030d9e361877c7bda

2020-12-21 13:31 UTC, closed without merging

2020-12-21 14:22 UTC, odivlad commented
@numansiddique, thanks.
May I know if this patch could be applied to supported branches? If needed, I can send PR to those branches in case of conflicts.

2020-12-22 07:32 UTC, numansiddique commented
@odivlad Since it is a feature/enhancement and not a bug fix. we don't normally backport to the branches.

How do you consume OVN ? If you build yourself, then I would suggest to backport this patch yourself.
If you consume from fedora/RDO, maybe we can do a backport  there.

2021-01-11 16:32 UTC, odivlad commented
We do build 20.06 by our internal build systems. Sure we can backport by ourself, but since there are changes in tests, each time there would be merge conflicts. If it's possible to backport, it would be appreciated. If not, well okay :)